### PR TITLE
Handle case where data is not present in content

### PR DESCRIPTION
**Pull request by Anmol-Gulati**
- Not every API request returns data in it's response specifically
    in case of errors.

Release checklist (if applicable)

- [ ] Issue(s) referenced (optional)
- [ ] Implementation done
- [ ] Changelog updated
- [ ] Version bump in `__about__.py`
- [ ] CI checks OK
- [ ] PR merged
- [ ] Branch deleted
- [ ] Tag added
- [ ] Release published

### CODE REVIEW

**Comment by Anmol-Gulati** [comment]
@ariebovenberg Requesting review, I was trying out this package for making graphql requests and found out this issue

**Comment by ariebovenberg** [comment]
@Anmol-Gulati thanks for the PR :). Will review. Currently feeling a bit under the weather so I will get to it later, but as soon as possible.

**Comment by Anmol-Gulati** [comment]
@ariebovenberg Thanks for accepting the patch.

On a side note, found another issue and now I feel NamedTuple is restricting the response keys. It is not always the case that there will be just 2 keys `errors` and `data`. Although they are most common

Each API is different and as a generic graphql library, it should not restrict responses

I am happy to send another patch which changes the implementation a bit

**Comment by Anmol-Gulati** [comment]
@ariebovenberg I agree with both the parts.

`errors` key will be present, if there are any errors
`data` will be present, if the request was successful

But the current implementation is only restricted to just these two keys. I just encountered the case where my request was Throtlled and there was an `extentions`  key describing the rate of request.

Anyways, I can write a patch in this weekend if I get time and will push for your review. :)

**Comment by ariebovenberg** [comment]
@Anmol-Gulati thanks for looking into it. You're very welcome to create a PR.

Following the spec, I'm thinking just the addition of an `extensions` field, with type `Optional[Dict[str, Any]]` should do. It's value can be set to ``None`` in case it is not present.

> The response map may also contain an entry with key `extensions`. This entry, if set, must have a map as its value. This entry is reserved for implementors to extend the protocol however they see fit, and hence there are no additional restrictions on its contents.

**Pull request merged**
